# Generated by Django 5.1.6 on 2025-03-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FanSupport', '0002_club_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
