# Generated by Django 5.1.7 on 2025-04-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FanSupport', '0005_ticket_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the ticket was last updated.'),
        ),
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateField(blank=True, help_text='Date the club was founded.', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.CharField(choices=[('LI', 'League of Ireland')], default='LI', help_text='League the club belongs to.', max_length=2),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Club logo image.', null=True, upload_to='club_logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Name of the football club.', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(blank=True, help_text="Name of the club's stadium.", max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Support agent assigned to this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('ticketing', 'Ticketing'), ('merchandise', 'Merchandise'), ('general', 'General Inquiry'), ('technical', 'Technical Issue'), ('billing', 'Billing')], default='general', help_text='Ticket category.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Club associated with the ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_tickets', to='FanSupport.club'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the ticket was created.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Detailed explanation of the issue.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', help_text='Priority level of the ticket.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ticket was resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Escalated', 'Escalated'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', help_text='Current status of the ticket.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(help_text='Brief subject of the ticket.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
